### ISSUE TITLE
Just a question || Is there an equivalent to this for c that you know about?

### ISSUE THREAD

**Issue by typkrft** [JoshCheek/atom-seeing-is-believing#16]
Sorry fi this isn't the right place, but as I am just starting to learn c this would been really neat to have. Thanks!
Brandon

**Comment by JoshCheek** [comment]
I don't know of one. A long time ago I saw debuggers for it, but haven't figured out how to reproduce it since then. Honestly, this would be difficult in C, it's not necessarily known what type some piece of data is. If you can reason about the types, you could make a macro or something, but if you can't (eg data from a `void*`), then it's just unknown binary content. I'm not sure how you would get access to that info, either. Maybe if the compiler supports plugins or something.

Anyway, your best bet there is a debugger, but I'm not a great person to ask about these things. If you find something, let me know, though. I especially am interested in being able to see the entire callstack :)
