### ISSUE TITLE
In Atom, how do you permanently configure a setting?

### ISSUE THREAD

**Issue by ckib16** [JoshCheek/atom-seeing-is-believing#33]
Hey @JoshCheek - I'm trying to decrease the timeout to 5"

I read the "Flags" section of the documentation.

I know the CLI command in terminal would be:
`seeing_is_believing -t 5`
Correct?

But, how do I get set that flag permanently so that it takes affect each time I open Atom?
Is there a certain `config` or `.rc` file in the Atom package that I need to modify to save the setting?

Maybe Atom's `config.cson`?

**Comment by JoshCheek** [comment]
In the settings, it shows the default flags that it's using, and when you click on it, it seems to fill them in (which is nice, b/c it'd be a bit of a PITA to have to retype all that), so then you can edit those flags, currently the last one is the timeout flag, it's set to 12, so we'll change it to 5 (I did 1.5 in the screencapture so that we didn't have to wait so long).

![sib-atom-change-timeout](https://cloud.githubusercontent.com/assets/77495/22729614/1d058ee8-eda9-11e6-9510-d7423ed48e7c.gif)

**Comment by ckib16** [comment]
Holy cow.

Ok - can we just forget I asked that :)

I must have looked for like 20' and it never occurred to me that the `Flags` section under "Settings" was "clickable". 

My bad. But thanks for the awesome gif!

**Comment by JoshCheek** [comment]
Np ^_^
